Feat Update multiple bus at one stop, Update bus boarding state
DeveloperAcademy-POSTECH/WidgetBus pull request #64
Opened 2022-12-02 13:53 UTC by HyeS00

## 📣 Related Issue

- close #8 

## 🌁 Background

뷰를 연결하기 위해 중간 PR을 올립니다. 

## 👩‍💻 Contents

- 한 정류장에 여러 대의 버스가 있는 것을 대응했습니다. 
- 노선 위의 버스들의 위치와 나의 위치의 거리를 측정해 제일 가까운 버스를 찾았습니다. 

## ✅ Testing

## 📱 Screenshot

![Simulator Screen Recording - iPhone 14 Pro - 2022-12-02 at 22 47 05](https://user-images.githubusercontent.com/67789254/205307266-65da9622-8fa3-4315-84da-cb4271d02b43.gif)
<img width="482" alt="스크린샷 2022-12-02 오후 10 48 46" src="https://user-images.githubusercontent.com/67789254/205307333-39be7a80-d2eb-407b-a295-a59477098699.png">

## 📝 Review Note

- 근처에 버스가 없는 경우 탑승을 눌렀을 때 반응이 없는 것보다 alert를 띄워주는 것이 어떨까 싶습니다.

- 아래의 경고는 많은 코드의 리팩토링을 요구하여 일단 뷰 연결이 급하다 판단해 우선 PR을 올립니다. 
<img width="530" alt="스크린샷 2022-12-02 오후 10 51 20" src="https://user-images.githubusercontent.com/67789254/205307864-e5f64022-66c5-41ff-a5c0-4a616a0c9b79.png">

## 📬 Reference

##

2022-12-03 01:31 UTC, shwoghk14 approved these changes
좋습니다.

2022-12-03 05:44 UTC, gojeongseog approved these changes
잘봤습니다 LGTM~

2022-12-03 15:20 UTC, jaehoon9186 approved these changes
LGTM ~

2022-12-05 02:18 UTC, Shin-jun approved these changes
고생하셨습니다~!

2022-12-05 07:27 UTC, minjae9610 commented
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) 델리게이트 직전 라인에 
// swiftlint:disable:next cyclomatic_complexity
주석을 사용한다면 임시로 해당 경고를 해제할 수 있습니다.

2022-12-05 07:50 UTC, minjae9610 requested changes
WidgetBus/Views/RouteDetailView/RouteDetailViewController.swift 의 368번 라인
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) 델리게이트 직전에
// swiftlint:disable:next cyclomatic_complexity 주석을 사용해주면 바로 아래 함수에 대해서 cyclomatic_complexity 워링을 표시하지 않습니다.
일단 이렇게 비활성해주시면 좋을거같아요!

2022-12-05 08:00 UTC, merged

2022-12-06 12:56 UTC, jaehoon9186 commented
ActivityIndicator 추가 예정